apiVersion: v1
kind: Service
metadata:
  name: ggap
  namespace: ginnungagap
  labels:
    app.kubernetes.io/name: ggap-node
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: ggap-node
  ports:
    - name: client
      port: 17000
      targetPort: client
      nodePort: 30700
