apiVersion: v1
kind: Service
metadata:
  name: ggap-admin
  namespace: ginnungagap
  labels:
    app.kubernetes.io/name: ggap-node
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: ggap-node
  ports:
    - name: cluster
      port: 17001
      targetPort: cluster
      nodePort: 30701
