apiVersion: v1
kind: Service
metadata:
  name: ggap-headless
  namespace: ginnungagap
  labels:
    app.kubernetes.io/name: ggap-node
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: ggap-node
  ports:
    - name: cluster
      port: 17001
      targetPort: cluster
    - name: metrics
      port: 9090
      targetPort: metrics
