apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-collector
  namespace: ginnungagap
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ginnungagap-otel-collector
rules:
  - apiGroups: [""]
    resources:
      - pods
      - services
      - endpoints
      - namespaces
      - nodes
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ginnungagap-otel-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ginnungagap-otel-collector
subjects:
  - kind: ServiceAccount
    name: otel-collector
    namespace: ginnungagap
