apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: ginnungagap
  labels:
    app.kubernetes.io/name: otel-collector
spec:
  selector:
    app.kubernetes.io/name: otel-collector
  ports:
    - name: self-metrics
      port: 8888
      targetPort: self-metrics
    - name: exported
      port: 8889
      targetPort: exported
